### ISSUE TITLE
Pkg.test("Metis") fails

### ISSUE THREAD

**Issue by sbromberger** [JuliaSparse/Metis.jl#11]
in 0.4:

```
 Runtime parameters:
   Objective type: METIS_OBJTYPE_NODE
   Coarsening type: METIS_CTYPE_SHEM
   Initial partitioning type: METIS_IPTYPE_EDGE
   Refinement type: METIS_RTYPE_SEP1SIDED
   Perform a 2-hop matching: No
   Number of balancing constraints: 1
   Number of refinement iterations: 10
   Random number seed: -1
   Number of separators: 1
   Compress graph prior to ordering: Yes
   Detect & order connected components separately: No
   Prunning factor for high degree vertices: 0.000000
   Allowed maximum load imbalance: 1.200

  Compression: reduction in # of vertices: 0.

Timing Information -------------------------------------------------
 Multilevel:           0.001
     Coarsening:           0.000
            Matching:              0.000
            Contract:              0.000
     Initial Partition:        0.000
     Uncoarsening:         0.000
          Refinement:              0.000
          Projection:              0.000
     Splitting:            0.000
********************************************************************

 gk_mcore statistics
           coresize:         1776         nmops:         2048  cmop:      0
        num_callocs:           64   num_hallocs:            0
       size_callocs:        14744  size_hallocs:            0
        cur_callocs:            0   cur_hallocs:            0
        max_callocs:         1608   max_hallocs:            0
 nbrpool statistics
        nbrpoolsize:            0   nbrpoolcpos:            0
    nbrpoolreallocs:            0

ERROR: LoadError: test failed: ([9029,9337,9086,9508,9180,9336] == [9076,9374,9384,9523,8978,9141])
 in expression: counts(part) == [9076,9374,9384,9523,8978,9141]
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/Metis/test/runtests.jl, in expression starting on line 26
```

in 0.3.5:

```
 Runtime parameters:
   Objective type: METIS_OBJTYPE_NODE
   Coarsening type: METIS_CTYPE_SHEM
   Initial partitioning type: METIS_IPTYPE_EDGE
   Refinement type: METIS_RTYPE_SEP1SIDED
   Perform a 2-hop matching: No
   Number of balancing constraints: 1
   Number of refinement iterations: 10
   Random number seed: -1
   Number of separators: 1
   Compress graph prior to ordering: Yes
   Detect & order connected components separately: No
   Prunning factor for high degree vertices: 0.000000
   Allowed maximum load imbalance: 1.200

  Compression: reduction in # of vertices: 0.

Timing Information -------------------------------------------------
 Multilevel:           0.001
     Coarsening:           0.000
            Matching:              0.000
            Contract:              0.000
     Initial Partition:        0.000
     Uncoarsening:         0.000
          Refinement:              0.000
          Projection:              0.000
     Splitting:            0.000
********************************************************************

 gk_mcore statistics
           coresize:         1776         nmops:         2048  cmop:      0
        num_callocs:           64   num_hallocs:            0
       size_callocs:        14744  size_hallocs:            0
        cur_callocs:            0   cur_hallocs:            0
        max_callocs:         1608   max_hallocs:            0
 nbrpool statistics
        nbrpoolsize:            0   nbrpoolcpos:            0
    nbrpoolreallocs:            0

ERROR: test failed: counts(part,6) == [9076,9374,9384,9523,8978,9141]
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in include at /usr/local/Cellar/julia/0.3.5_1/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /usr/local/Cellar/julia/0.3.5_1/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.3.5_1/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.3/Metis/test/runtests.jl, in expression starting on line 28
```

**Comment by poulson** [comment]
On the bright side, this seems to not be related to my recent additions; on the other side, I'm not familiar enough with 0.4 to know might what have broken without spending some quality time. @dmbates ?

**Comment by sbromberger** [comment]
To clarify: testing is broken on 0.3.5 as well... just in a different place (?)

**Comment by poulson** [comment]
Thanks; I read too quickly. It still seems to be in the k-way partitioning, which is orthogonal to my changes.

**Comment by sbromberger** [comment]
The only reason I filed this issue was because I was getting ready to submit a PR to allow k-way partitioning to accept adjacency matrices, and tests failed, so I reverted, and tests still failed....

On second thought, let me do a Pkg.checkout() to make sure I have the latest code regardless of tag.

**Comment by dmbates** [comment]
The test is failing because the results of the k-way partitioning are not the same as when I ran the test on an Ubuntu amd64 system.
```
ERROR: LoadError: test failed: ([9029,9337,9086,9508,9180,9336] == [9076,9374,9384,9523,8978,9141])
 in expression: counts(part) == [9076,9374,9384,9523,8978,9141]
```
[9076,...] is the vector of counts of nodes in the 6 partitions when I ran the k-way partitioning.  I had thought that the result was deterministic.  Does it make sense that it is non-deterministic?

@sbromberger, is there a way of checking what version of the Metis library you are using?

**Comment by sbromberger** [comment]
I found this in ~/.julia/v0.4/Metis/deps/usr/include/metis.h:

```
#define METIS_VER_MAJOR         5
#define METIS_VER_MINOR         1
#define METIS_VER_SUBMINOR      0
```

**Comment by sbromberger** [comment]
What's interesting to me is that travis isn't complaining. @dmbates - is Pkg.test() working on your system? Perhaps it's just me?

**Comment by poulson** [comment]
@dmbates In that case, I would recommend changing the test to verify that the k-way partition is valid rather than equal to a particular choice. This is what I have done with ``vertexSep``.

**Comment by dmbates** [comment]
@sbromberger `Pkg.test("Metis")` is successful on my system.  Of course, the comparison results are those from my system so the test should succeed.  The Travis tests are also performed using the Debian/Ubuntu package `libmetis5` and should be expected to succeed.

What OS are you testing on?

**Comment by dmbates** [comment]
@poulson I will modify the test as you suggest.

**Comment by sbromberger** [comment]
OSX 10.10.2.

**Comment by sbromberger** [comment]
Confirmed that tests pass on my ubuntu machine (libmetis5.1.0).

**Comment by dmbates** [comment]
@poulson After having said I would modify the tests I don't know what to check for in the partition returned from `partGraphKway` or `partGraphRecursive`.  I can see in the results of `vertexSep` that vertices in group 0 should not have edges to vertices in group 1 and vice-versa.  The only connections between those groups should go through vertices in group 2. 

But I don't know what the characteristics of a K-way partition should be, other than each node should be in one of the partitions and each partition should contain at least one node.  Is there anything else I should check for?

**Comment by sbromberger** [comment]
At a very fundamental level, could you check that length(ans) is the expected number of partitions?

**Comment by poulson** [comment]
@dmbates You're right that the check needs to be different, and that the validity of the partition (in the sense that each node is in exactly one subset) is the main thing to check. In addition, one could check the size of the interface (the set of all nodes in one subset but connected to another) and complain if it is significantly larger than on your machine.

**Comment by dmbates** [comment]
The way that the result is returned ensures that each node can be in only one subset.  Checking that there are the correct number of subsets and that the subsets are non-empty is straightforward.  I will need to add another function to evaluate the size of the interface.
