### ISSUE TITLE
For discussion: could I change the parameters for function partGraphKway and partGraphRecursive?

### ISSUE THREAD

**Issue by sbromberger** [JuliaSparse/Metis.jl#13]
I notice that these functions require an adjacency list, which is a type specific to Graphs.jl. Since `metisform` is available for sparse matrices and you're calling `metisform` on `al` anyway, would you mind terribly a PR that would generalize the parameter to mirror `nodeND(x,verbose::Integer=0)`? That way any type that can be `metisform`ed can be used with the partitioning functions.

This opens Metis up to LightGraphs.jl, which provides adjacency matrices in the form of `SparseMatrixCSC`.

**Comment by dmbates** [comment]
@sbromberger Certainly it would make sense to have `partGraphKway` and `partGraphRecursive` call `metisform`.  In fact, if that is done then you would not need to go through `SparseMatrixCSC` in LightGraphs.jl.  All you need to do is to add a method for `Metis.metisform`, although that would mean that LightGraphs  should list `Metis` in its `REQUIRE` file.

**Comment by sbromberger** [comment]
So, the thing is, they already DO call metisform. The only change I'm proposing is the argument type. Right now it's `partGraphKway(al::GenericAdjacencyList, nparts::Integer)` and the first thing the function does is call `n, xadj, adjncy = metisform(al)`. If we removed the type specification for the first argument, any dispatch on metisform would suddenly, magically, work :)

I will create a PR for this then. Thanks.

**Comment by sbromberger** [comment]
Closing due to merge of #14.
