### ISSUE TITLE
How to deal with a weighted graph

### ISSUE THREAD

**Issue by tsano430** [JuliaSparse/Metis.jl#35]
Hello, is there a way to give edge weights to `Metis.partition()`?

**Comment by rocarvaj** [comment]
Hi! This will require you to fork the project. In theory you just need to modify the calls to `METIS_PartGraphRecursive` and `METIS_PartGraphKway` in `Metis.partition()` and add the edge weights (see Section 5.8 of the METIS manual for the parameter list). You just have to keep in mind that the vector with the edge weights has to be in the CSR format.

I've opened a PR (#37) where I added a basic support for using graph from [SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl). It should be what you need. Check it out.

Hope this helps!

**Comment by tsano430** [comment]
@rocarvaj That would be great. Thanks!

**Comment by tsano430** [comment]
I run the following code, and then obtain an error. 

```julia
julia> using Metis, SimpleWeightedGraphs

julia> S = [4 3 2 1 0 0 0;
            3 4 2 0 1 0 0;
            2 2 3 1 0 0 0;
            1 0 1 4 2 0 0;
            0 1 0 2 4 1 1;
            0 0 0 0 1 3 3;
            0 0 0 0 1 3 3]; # adjacency matrix

julia> G = SimpleWeightedGraph(S);

julia> Metis.partition(G, 3)
ERROR: BoundsError: attempt to access 26-element Array{Int32,1} at index [27]
Stacktrace:
 [1] setindex! at ./array.jl:847 [inlined]
 [2] graph(::SimpleWeightedGraph{Int64,Float64}) at /Users/tsano/Metis.jl/src/Metis.jl:107
 [3] #partition#2 at /Users/tsano/Metis.jl/src/Metis.jl:146 [inlined]
 [4] partition(::SimpleWeightedGraph{Int64,Float64}, ::Int64) at /Users/tsano/Metis.jl/src/Metis.jl:146
 [5] top-level scope at REPL[5]:1
```

Do you have any idea how to fix this?

**Comment by tsano430** [comment]
I found the cause of the error. The details will be described in the corresponding PR.
