### ISSUE TITLE
Nodal bisection?

### ISSUE THREAD

**Issue by poulson** [JuliaSparse/Metis.jl#4]
I am hoping to teach how to build a basic sparse-direct Cholesky factorization natively in Julia, with the only significant external function being a nodal bisection. In Elemental, I have manually extended METIS to provide this functionality: https://github.com/elemental/Elemental/blob/e9a4ff1192f2db55b69e80703732a498e8dad44d/src/lapack_like/factor/sparse/symbolic/ElOrder.c

Is there some way to get a clean API for a nodal bisection within Metis.jl?

**Comment by poulson** [comment]
I haven't tested the following commit, but I think I might have solved the problem:
    https://github.com/poulson/Metis.jl/commit/40c2f30ffc0d5a283dae8b9a3a8e88af25611e5a

**Comment by dmbates** [comment]
Does the addition of the `vertexSep` function close this issue?

**Comment by poulson** [comment]
Yes! Sorry for not remembering to close this.
