### ISSUE TITLE
Unable to Visualize Graphs

### ISSUE THREAD

**Issue by BrettKnoss** [JuliaSparse/Metis.jl#43]
```julia> g=SimpleDiGraph(4)
{4, 0} directed simple Int64 graph

julia> add_edge!(g,1,2)
true
```
gives me a vector, but not the visual graph as shown in the example.  Is this supposed to visualize a graph, and do I need to download any software to do so?

**Comment by fredrikekre** [comment]
Seems unrelated to this package.

**Comment by BrettKnoss** [comment]
Ok thanks.  I've since figured out that GraphPlot.jl is for visualization.
