### ISSUE TITLE
partition meshes?

### ISSUE THREAD

**Issue by vavrines** [JuliaSparse/Metis.jl#47]
The README mentions partitioning meshes, but I didn't find an examplesor test.
Is this feature already supported or not?

**Comment by fredrikekre** [comment]
Metis doesn't support a specific mesh structure, but if you construt the connectivity graph between your elements you can use it to partition.

**Comment by vavrines** [comment]
> but if you construt the connectivity graph between your elements you can use it to partition

I believe an illustrative example similar to the one shown in pymetis will be helpful, if you want.
