### ISSUE TITLE
Error if requesting 1 partition

### ISSUE THREAD

**Issue by JoeyT1994** [JuliaSparse/Metis.jl#49]
Metis.jl throws an error if the requested number of partitions is 1. 

E.g:

```
using Graphs
using Metis
Metis.partition(path_graph(6), 1)
```

throws:
![image](https://user-images.githubusercontent.com/51231103/213310324-b1524962-c7fc-408c-ace8-28aa37d82af2.png)

Whilst this is an edge case, the algorithm should still return something meaningful.

I am unsure if this is also an error in the original library (seems likely, KaHyPar had a similar issue - see https://github.com/kahypar/kahypar/issues/139#).

**Comment by fredrikekre** [comment]
Thanks for the report. I also noticed this not long ago, but couldn't figure out where the error comes from. Why do you think it is an error in Metis the C library though? Does KaHyPar use Metis too?

**Comment by JoeyT1994** [comment]
Oh no it was just that in the case of KaHyPar the error was in both the Julia and C++ versions - and so I imagine it could be here. I haven't tried the C version of Metis so I am just guessing - it might be localised to the Julia version.

**Comment by fredrikekre** [comment]
It is really strange, the error comes from https://github.com/JuliaSparse/Metis.jl/blob/fcd76832c0430b412711006b040eaeec7c97bf8c/lib/LibMetis.jl#L17. The error is a Julia error, but happens in the invocation of `ccall` somehow.
