### ISSUE TITLE
Off-by-one error in vertexSep

### ISSUE THREAD

**Issue by dmbates** [JuliaSparse/Metis.jl#9]
It seems that the `SparseMatrixCSC` method for `vertexSep` uses 0-based numbering on the vertices and adjacency list for compatibility with ParMETIS.  But the METIS_OPTION_NUMBERING position in the metis_options vector has been set to 1 and, as far as I can see, never reset.

I think I will go ahead with the plan to create 0-based CSR representations of the adjacency list from a SparseMatrixCSC object as I mentioned in issue #8

**Comment by poulson** [comment]
Good point, but, in the mean time, we might as well commit the one-line changeset to fix the current version.

**Comment by poulson** [comment]
After thinking about the issue further, I think the code is fine as-is. The reason is that ``METIS_ComputeVertexSeparator`` ignores ``options[METIS_OPTION_NUMBERING]``; it would be silly to temporarily set the value to zero in a small codeblock surrounding the ``METIS_ComputeVertexSeparator`` call.

**Comment by dmbates** [comment]
The approach in the 0-based branch is to have all the indices 0-based.  I'll make a PR out of that branch but right now this issue can be closed.
